### PR TITLE
Added gettext mo

### PR DESCRIPTION
**Pull request by KOLANICH**
For how it doesn't work because of the bug in the compiler. If I replaced endianness selection logic with `le`, it works.

### CODE REVIEW

**Comment by KOLANICH** [comment]
Seems to be ready

**Comment by KOLANICH** [comment]
@GreyCat

**Comment by GreyCat** [comment]
Thanks for this contribution. Please note that I'll apply a set of fixes on top of your file.

**Comment by KOLANICH** [comment]
>Please note that I'll apply a set of fixes on top of your file.

Thank you for the warning.

**Pull request merged**
