### PR TITLE
Various Mach-O fixes

### PR DESCRIPTION
**Pull request by tchebb**
See specific commit messages for details. These are all bugfixes and trivial features.

This contribution is on behalf of my company, unlike my prior ones. I will note when the case for this and all future PRs.

### CODE REVIEW

**Comment by tchebb** [comment]
Rebased to fix merge conflict in `meta` section from #516.

**Comment by knmueller** [comment]
@tchebb Any idea if there is a reason this is being held and not already merged? I am using the MachO parser and noticed these enhancements.

**Comment by tchebb** [comment]
@knmueller I don't know; guessing the maintainers are overwhelmed or busy. These fixes are still useful and correct as far as I'm aware.

**Review by generalmimon — APPROVED** [review]
@tchebb Thanks! Looks good to me, I'll just fix some of the links afterwards. Sorry for the delay.

**Pull request merged**
